; Listing generated by Microsoft (R) Optimizing Compiler Version 19.26.28805.0 

	TITLE	C:\Users\hank2\source\repos\zlib\inffast.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

END
